// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: tikr.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tikr_IngestTicks_FullMethodName = "/tikr.v1.Tikr/IngestTicks"
	Tikr_QueryTicks_FullMethodName  = "/tikr.v1.Tikr/QueryTicks"
	Tikr_QueryBars_FullMethodName   = "/tikr.v1.Tikr/QueryBars"
	Tikr_ListSeries_FullMethodName  = "/tikr.v1.Tikr/ListSeries"
	Tikr_GetInfo_FullMethodName     = "/tikr.v1.Tikr/GetInfo"
)

// TikrClient is the client API for Tikr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TikrClient interface {
	// Streaming ingest — client sends a stream of IngestRequests.
	IngestTicks(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IngestRequest, IngestResponse], error)
	// Query raw ticks in a time range.
	QueryTicks(ctx context.Context, in *TickQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TickData], error)
	// Query rolled-up bars in a time range.
	QueryBars(ctx context.Context, in *BarQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BarData], error)
	// List all configured series.
	ListSeries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SeriesList, error)
	// Get server info.
	GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerInfo, error)
}

type tikrClient struct {
	cc grpc.ClientConnInterface
}

func NewTikrClient(cc grpc.ClientConnInterface) TikrClient {
	return &tikrClient{cc}
}

func (c *tikrClient) IngestTicks(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IngestRequest, IngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tikr_ServiceDesc.Streams[0], Tikr_IngestTicks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestRequest, IngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tikr_IngestTicksClient = grpc.ClientStreamingClient[IngestRequest, IngestResponse]

func (c *tikrClient) QueryTicks(ctx context.Context, in *TickQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TickData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tikr_ServiceDesc.Streams[1], Tikr_QueryTicks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TickQuery, TickData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tikr_QueryTicksClient = grpc.ServerStreamingClient[TickData]

func (c *tikrClient) QueryBars(ctx context.Context, in *BarQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BarData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tikr_ServiceDesc.Streams[2], Tikr_QueryBars_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BarQuery, BarData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tikr_QueryBarsClient = grpc.ServerStreamingClient[BarData]

func (c *tikrClient) ListSeries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SeriesList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeriesList)
	err := c.cc.Invoke(ctx, Tikr_ListSeries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tikrClient) GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerInfo)
	err := c.cc.Invoke(ctx, Tikr_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TikrServer is the server API for Tikr service.
// All implementations must embed UnimplementedTikrServer
// for forward compatibility.
type TikrServer interface {
	// Streaming ingest — client sends a stream of IngestRequests.
	IngestTicks(grpc.ClientStreamingServer[IngestRequest, IngestResponse]) error
	// Query raw ticks in a time range.
	QueryTicks(*TickQuery, grpc.ServerStreamingServer[TickData]) error
	// Query rolled-up bars in a time range.
	QueryBars(*BarQuery, grpc.ServerStreamingServer[BarData]) error
	// List all configured series.
	ListSeries(context.Context, *Empty) (*SeriesList, error)
	// Get server info.
	GetInfo(context.Context, *Empty) (*ServerInfo, error)
	mustEmbedUnimplementedTikrServer()
}

// UnimplementedTikrServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTikrServer struct{}

func (UnimplementedTikrServer) IngestTicks(grpc.ClientStreamingServer[IngestRequest, IngestResponse]) error {
	return status.Error(codes.Unimplemented, "method IngestTicks not implemented")
}
func (UnimplementedTikrServer) QueryTicks(*TickQuery, grpc.ServerStreamingServer[TickData]) error {
	return status.Error(codes.Unimplemented, "method QueryTicks not implemented")
}
func (UnimplementedTikrServer) QueryBars(*BarQuery, grpc.ServerStreamingServer[BarData]) error {
	return status.Error(codes.Unimplemented, "method QueryBars not implemented")
}
func (UnimplementedTikrServer) ListSeries(context.Context, *Empty) (*SeriesList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSeries not implemented")
}
func (UnimplementedTikrServer) GetInfo(context.Context, *Empty) (*ServerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedTikrServer) mustEmbedUnimplementedTikrServer() {}
func (UnimplementedTikrServer) testEmbeddedByValue()              {}

// UnsafeTikrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TikrServer will
// result in compilation errors.
type UnsafeTikrServer interface {
	mustEmbedUnimplementedTikrServer()
}

func RegisterTikrServer(s grpc.ServiceRegistrar, srv TikrServer) {
	// If the following call panics, it indicates UnimplementedTikrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tikr_ServiceDesc, srv)
}

func _Tikr_IngestTicks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TikrServer).IngestTicks(&grpc.GenericServerStream[IngestRequest, IngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tikr_IngestTicksServer = grpc.ClientStreamingServer[IngestRequest, IngestResponse]

func _Tikr_QueryTicks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TickQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TikrServer).QueryTicks(m, &grpc.GenericServerStream[TickQuery, TickData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tikr_QueryTicksServer = grpc.ServerStreamingServer[TickData]

func _Tikr_QueryBars_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BarQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TikrServer).QueryBars(m, &grpc.GenericServerStream[BarQuery, BarData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tikr_QueryBarsServer = grpc.ServerStreamingServer[BarData]

func _Tikr_ListSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikrServer).ListSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tikr_ListSeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikrServer).ListSeries(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tikr_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikrServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tikr_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikrServer).GetInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Tikr_ServiceDesc is the grpc.ServiceDesc for Tikr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tikr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tikr.v1.Tikr",
	HandlerType: (*TikrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSeries",
			Handler:    _Tikr_ListSeries_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _Tikr_GetInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestTicks",
			Handler:       _Tikr_IngestTicks_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "QueryTicks",
			Handler:       _Tikr_QueryTicks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "QueryBars",
			Handler:       _Tikr_QueryBars_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tikr.proto",
}
