// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: tikr.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        string                 `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
	Ticks         []*TickData            `protobuf:"bytes,2,rep,name=ticks,proto3" json:"ticks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_tikr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tikr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_tikr_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *IngestRequest) GetTicks() []*TickData {
	if x != nil {
		return x.Ticks
	}
	return nil
}

type TickData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   uint64                 `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Dimensions    map[string]string      `protobuf:"bytes,2,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fields        map[string]int64       `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Sequence      uint32                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickData) Reset() {
	*x = TickData{}
	mi := &file_tikr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickData) ProtoMessage() {}

func (x *TickData) ProtoReflect() protoreflect.Message {
	mi := &file_tikr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickData.ProtoReflect.Descriptor instead.
func (*TickData) Descriptor() ([]byte, []int) {
	return file_tikr_proto_rawDescGZIP(), []int{1}
}

func (x *TickData) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *TickData) GetDimensions() map[string]string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *TickData) GetFields() map[string]int64 {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *TickData) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicksReceived uint64                 `protobuf:"varint,1,opt,name=ticks_received,json=ticksReceived,proto3" json:"ticks_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_tikr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tikr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_tikr_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetTicksReceived() uint64 {
	if x != nil {
		return x.TicksReceived
	}
	return 0
}

type TickQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        string                 `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
	Dimensions    map[string]string      `protobuf:"bytes,2,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StartNs       uint64                 `protobuf:"varint,3,opt,name=start_ns,json=startNs,proto3" json:"start_ns,omitempty"`
	EndNs         uint64                 `protobuf:"varint,4,opt,name=end_ns,json=endNs,proto3" json:"end_ns,omitempty"`
	Limit         uint32                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickQuery) Reset() {
	*x = TickQuery{}
	mi := &file_tikr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickQuery) ProtoMessage() {}

func (x *TickQuery) ProtoReflect() protoreflect.Message {
	mi := &file_tikr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickQuery.ProtoReflect.Descriptor instead.
func (*TickQuery) Descriptor() ([]byte, []int) {
	return file_tikr_proto_rawDescGZIP(), []int{3}
}

func (x *TickQuery) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *TickQuery) GetDimensions() map[string]string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *TickQuery) GetStartNs() uint64 {
	if x != nil {
		return x.StartNs
	}
	return 0
}

func (x *TickQuery) GetEndNs() uint64 {
	if x != nil {
		return x.EndNs
	}
	return 0
}

func (x *TickQuery) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BarQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        string                 `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
	Dimensions    map[string]string      `protobuf:"bytes,2,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StartNs       uint64                 `protobuf:"varint,3,opt,name=start_ns,json=startNs,proto3" json:"start_ns,omitempty"`
	EndNs         uint64                 `protobuf:"varint,4,opt,name=end_ns,json=endNs,proto3" json:"end_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarQuery) Reset() {
	*x = BarQuery{}
	mi := &file_tikr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarQuery) ProtoMessage() {}

func (x *BarQuery) ProtoReflect() protoreflect.Message {
	mi := &file_tikr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarQuery.ProtoReflect.Descriptor instead.
func (*BarQuery) Descriptor() ([]byte, []int) {
	return file_tikr_proto_rawDescGZIP(), []int{4}
}

func (x *BarQuery) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *BarQuery) GetDimensions() map[string]string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *BarQuery) GetStartNs() uint64 {
	if x != nil {
		return x.StartNs
	}
	return 0
}

func (x *BarQuery) GetEndNs() uint64 {
	if x != nil {
		return x.EndNs
	}
	return 0
}

type BarData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Series         string                 `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
	BucketTs       uint64                 `protobuf:"varint,2,opt,name=bucket_ts,json=bucketTs,proto3" json:"bucket_ts,omitempty"`
	Dimensions     map[string]string      `protobuf:"bytes,3,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metrics        map[string]int64       `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FirstTimestamp uint64                 `protobuf:"varint,5,opt,name=first_timestamp,json=firstTimestamp,proto3" json:"first_timestamp,omitempty"`
	LastTimestamp  uint64                 `protobuf:"varint,6,opt,name=last_timestamp,json=lastTimestamp,proto3" json:"last_timestamp,omitempty"`
	TickCount      uint64                 `protobuf:"varint,7,opt,name=tick_count,json=tickCount,proto3" json:"tick_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BarData) Reset() {
	*x = BarData{}
	mi := &file_tikr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarData) ProtoMessage() {}

func (x *BarData) ProtoReflect() protoreflect.Message {
	mi := &file_tikr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarData.ProtoReflect.Descriptor instead.
func (*BarData) Descriptor() ([]byte, []int) {
	return file_tikr_proto_rawDescGZIP(), []int{5}
}

func (x *BarData) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *BarData) GetBucketTs() uint64 {
	if x != nil {
		return x.BucketTs
	}
	return 0
}

func (x *BarData) GetDimensions() map[string]string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *BarData) GetMetrics() map[string]int64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *BarData) GetFirstTimestamp() uint64 {
	if x != nil {
		return x.FirstTimestamp
	}
	return 0
}

func (x *BarData) GetLastTimestamp() uint64 {
	if x != nil {
		return x.LastTimestamp
	}
	return 0
}

func (x *BarData) GetTickCount() uint64 {
	if x != nil {
		return x.TickCount
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_tikr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_tikr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_tikr_proto_rawDescGZIP(), []int{6}
}

type SeriesInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dimensions    []string               `protobuf:"bytes,2,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	Metrics       []string               `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Rollup        string                 `protobuf:"bytes,4,opt,name=rollup,proto3" json:"rollup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesInfo) Reset() {
	*x = SeriesInfo{}
	mi := &file_tikr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesInfo) ProtoMessage() {}

func (x *SeriesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tikr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesInfo.ProtoReflect.Descriptor instead.
func (*SeriesInfo) Descriptor() ([]byte, []int) {
	return file_tikr_proto_rawDescGZIP(), []int{7}
}

func (x *SeriesInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SeriesInfo) GetDimensions() []string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *SeriesInfo) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *SeriesInfo) GetRollup() string {
	if x != nil {
		return x.Rollup
	}
	return ""
}

type SeriesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*SeriesInfo          `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesList) Reset() {
	*x = SeriesList{}
	mi := &file_tikr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesList) ProtoMessage() {}

func (x *SeriesList) ProtoReflect() protoreflect.Message {
	mi := &file_tikr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesList.ProtoReflect.Descriptor instead.
func (*SeriesList) Descriptor() ([]byte, []int) {
	return file_tikr_proto_rawDescGZIP(), []int{8}
}

func (x *SeriesList) GetSeries() []*SeriesInfo {
	if x != nil {
		return x.Series
	}
	return nil
}

type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds uint64                 `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Series        []*SeriesInfo          `protobuf:"bytes,3,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_tikr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tikr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_tikr_proto_rawDescGZIP(), []int{9}
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfo) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ServerInfo) GetSeries() []*SeriesInfo {
	if x != nil {
		return x.Series
	}
	return nil
}

var File_tikr_proto protoreflect.FileDescriptor

const file_tikr_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"tikr.proto\x12\atikr.v1\"P\n" +
	"\rIngestRequest\x12\x16\n" +
	"\x06series\x18\x01 \x01(\tR\x06series\x12'\n" +
	"\x05ticks\x18\x02 \x03(\v2\x11.tikr.v1.TickDataR\x05ticks\"\xbd\x02\n" +
	"\bTickData\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x04R\vtimestampNs\x12A\n" +
	"\n" +
	"dimensions\x18\x02 \x03(\v2!.tikr.v1.TickData.DimensionsEntryR\n" +
	"dimensions\x125\n" +
	"\x06fields\x18\x03 \x03(\v2\x1d.tikr.v1.TickData.FieldsEntryR\x06fields\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\rR\bsequence\x1a=\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"7\n" +
	"\x0eIngestResponse\x12%\n" +
	"\x0eticks_received\x18\x01 \x01(\x04R\rticksReceived\"\xee\x01\n" +
	"\tTickQuery\x12\x16\n" +
	"\x06series\x18\x01 \x01(\tR\x06series\x12B\n" +
	"\n" +
	"dimensions\x18\x02 \x03(\v2\".tikr.v1.TickQuery.DimensionsEntryR\n" +
	"dimensions\x12\x19\n" +
	"\bstart_ns\x18\x03 \x01(\x04R\astartNs\x12\x15\n" +
	"\x06end_ns\x18\x04 \x01(\x04R\x05endNs\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\x1a=\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x01\n" +
	"\bBarQuery\x12\x16\n" +
	"\x06series\x18\x01 \x01(\tR\x06series\x12A\n" +
	"\n" +
	"dimensions\x18\x02 \x03(\v2!.tikr.v1.BarQuery.DimensionsEntryR\n" +
	"dimensions\x12\x19\n" +
	"\bstart_ns\x18\x03 \x01(\x04R\astartNs\x12\x15\n" +
	"\x06end_ns\x18\x04 \x01(\x04R\x05endNs\x1a=\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x03\n" +
	"\aBarData\x12\x16\n" +
	"\x06series\x18\x01 \x01(\tR\x06series\x12\x1b\n" +
	"\tbucket_ts\x18\x02 \x01(\x04R\bbucketTs\x12@\n" +
	"\n" +
	"dimensions\x18\x03 \x03(\v2 .tikr.v1.BarData.DimensionsEntryR\n" +
	"dimensions\x127\n" +
	"\ametrics\x18\x04 \x03(\v2\x1d.tikr.v1.BarData.MetricsEntryR\ametrics\x12'\n" +
	"\x0ffirst_timestamp\x18\x05 \x01(\x04R\x0efirstTimestamp\x12%\n" +
	"\x0elast_timestamp\x18\x06 \x01(\x04R\rlastTimestamp\x12\x1d\n" +
	"\n" +
	"tick_count\x18\a \x01(\x04R\ttickCount\x1a=\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\a\n" +
	"\x05Empty\"r\n" +
	"\n" +
	"SeriesInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x02 \x03(\tR\n" +
	"dimensions\x12\x18\n" +
	"\ametrics\x18\x03 \x03(\tR\ametrics\x12\x16\n" +
	"\x06rollup\x18\x04 \x01(\tR\x06rollup\"9\n" +
	"\n" +
	"SeriesList\x12+\n" +
	"\x06series\x18\x01 \x03(\v2\x13.tikr.v1.SeriesInfoR\x06series\"z\n" +
	"\n" +
	"ServerInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x04R\ruptimeSeconds\x12+\n" +
	"\x06series\x18\x03 \x03(\v2\x13.tikr.v1.SeriesInfoR\x06series2\x96\x02\n" +
	"\x04Tikr\x12@\n" +
	"\vIngestTicks\x12\x16.tikr.v1.IngestRequest\x1a\x17.tikr.v1.IngestResponse(\x01\x125\n" +
	"\n" +
	"QueryTicks\x12\x12.tikr.v1.TickQuery\x1a\x11.tikr.v1.TickData0\x01\x122\n" +
	"\tQueryBars\x12\x11.tikr.v1.BarQuery\x1a\x10.tikr.v1.BarData0\x01\x121\n" +
	"\n" +
	"ListSeries\x12\x0e.tikr.v1.Empty\x1a\x13.tikr.v1.SeriesList\x12.\n" +
	"\aGetInfo\x12\x0e.tikr.v1.Empty\x1a\x13.tikr.v1.ServerInfoB'Z%github.com/walkerfunction/tikr/pkg/pbb\x06proto3"

var (
	file_tikr_proto_rawDescOnce sync.Once
	file_tikr_proto_rawDescData []byte
)

func file_tikr_proto_rawDescGZIP() []byte {
	file_tikr_proto_rawDescOnce.Do(func() {
		file_tikr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tikr_proto_rawDesc), len(file_tikr_proto_rawDesc)))
	})
	return file_tikr_proto_rawDescData
}

var file_tikr_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_tikr_proto_goTypes = []any{
	(*IngestRequest)(nil),  // 0: tikr.v1.IngestRequest
	(*TickData)(nil),       // 1: tikr.v1.TickData
	(*IngestResponse)(nil), // 2: tikr.v1.IngestResponse
	(*TickQuery)(nil),      // 3: tikr.v1.TickQuery
	(*BarQuery)(nil),       // 4: tikr.v1.BarQuery
	(*BarData)(nil),        // 5: tikr.v1.BarData
	(*Empty)(nil),          // 6: tikr.v1.Empty
	(*SeriesInfo)(nil),     // 7: tikr.v1.SeriesInfo
	(*SeriesList)(nil),     // 8: tikr.v1.SeriesList
	(*ServerInfo)(nil),     // 9: tikr.v1.ServerInfo
	nil,                    // 10: tikr.v1.TickData.DimensionsEntry
	nil,                    // 11: tikr.v1.TickData.FieldsEntry
	nil,                    // 12: tikr.v1.TickQuery.DimensionsEntry
	nil,                    // 13: tikr.v1.BarQuery.DimensionsEntry
	nil,                    // 14: tikr.v1.BarData.DimensionsEntry
	nil,                    // 15: tikr.v1.BarData.MetricsEntry
}
var file_tikr_proto_depIdxs = []int32{
	1,  // 0: tikr.v1.IngestRequest.ticks:type_name -> tikr.v1.TickData
	10, // 1: tikr.v1.TickData.dimensions:type_name -> tikr.v1.TickData.DimensionsEntry
	11, // 2: tikr.v1.TickData.fields:type_name -> tikr.v1.TickData.FieldsEntry
	12, // 3: tikr.v1.TickQuery.dimensions:type_name -> tikr.v1.TickQuery.DimensionsEntry
	13, // 4: tikr.v1.BarQuery.dimensions:type_name -> tikr.v1.BarQuery.DimensionsEntry
	14, // 5: tikr.v1.BarData.dimensions:type_name -> tikr.v1.BarData.DimensionsEntry
	15, // 6: tikr.v1.BarData.metrics:type_name -> tikr.v1.BarData.MetricsEntry
	7,  // 7: tikr.v1.SeriesList.series:type_name -> tikr.v1.SeriesInfo
	7,  // 8: tikr.v1.ServerInfo.series:type_name -> tikr.v1.SeriesInfo
	0,  // 9: tikr.v1.Tikr.IngestTicks:input_type -> tikr.v1.IngestRequest
	3,  // 10: tikr.v1.Tikr.QueryTicks:input_type -> tikr.v1.TickQuery
	4,  // 11: tikr.v1.Tikr.QueryBars:input_type -> tikr.v1.BarQuery
	6,  // 12: tikr.v1.Tikr.ListSeries:input_type -> tikr.v1.Empty
	6,  // 13: tikr.v1.Tikr.GetInfo:input_type -> tikr.v1.Empty
	2,  // 14: tikr.v1.Tikr.IngestTicks:output_type -> tikr.v1.IngestResponse
	1,  // 15: tikr.v1.Tikr.QueryTicks:output_type -> tikr.v1.TickData
	5,  // 16: tikr.v1.Tikr.QueryBars:output_type -> tikr.v1.BarData
	8,  // 17: tikr.v1.Tikr.ListSeries:output_type -> tikr.v1.SeriesList
	9,  // 18: tikr.v1.Tikr.GetInfo:output_type -> tikr.v1.ServerInfo
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_tikr_proto_init() }
func file_tikr_proto_init() {
	if File_tikr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tikr_proto_rawDesc), len(file_tikr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tikr_proto_goTypes,
		DependencyIndexes: file_tikr_proto_depIdxs,
		MessageInfos:      file_tikr_proto_msgTypes,
	}.Build()
	File_tikr_proto = out.File
	file_tikr_proto_goTypes = nil
	file_tikr_proto_depIdxs = nil
}
